import { randomInt } from "crypto";
import { generateServerSeed, hashServerSeed, generateClientSeed, deriveDiceClash, deriveCoinFlip, generateVerificationId } from "../provablyFair";
import { db } from "../../../db";
import { debitWallet, creditWallet, writeLedgerEntry } from "../../wallets/wallets.service";
import { getConfigValue, getGameFeeRate } from "../../admin/config/admin.config.service";
import { recordGameResult } from "../settlement";
import { createGameFeeJobInTx } from "../../affiliates/commissions";
import { activateReferral } from "../../referrals/referrals.service";

// Waiting players heartbeat through polling. The lease is deliberately longer than
// a normal browser/network hiccup so a legitimate player is not kicked while the
// backend is waking from a Render Free cold start or a request is delayed.
const QUEUE_TTL_MS = 5 * 60_000;
const SIGNAL_DELAY_MS = [1000, 2000, 3000, 4000, 5000];
const REACTION_TAP_TIMEOUT_MS = 20_000;
export type MatchGameType = "dice_clash" | "pvp_coinflip" | "reaction_tap";

export function startQueueCleanup(): void {
  setInterval(() => {
    (async () => {
      const expired = await db.matchmakingQueue.findMany({ where: { status: { in: ["waiting", "reserved"] }, expiresAt: { lt: new Date() } }, take: 100 });
      for (const entry of expired) {
        if (entry.status === "reserved") await db.$transaction(async tx => { const claimed = await tx.matchmakingQueue.updateMany({ where: { id: entry.id, status: "reserved" }, data: { status: "cancelled" } }); if (claimed.count) await creditWallet(tx, entry.userId, "game", entry.stake); }).catch(() => {});
        else await db.matchmakingQueue.updateMany({ where: { id: entry.id, status: "waiting" }, data: { status: "cancelled" } }).catch(() => {});
      }
      await recoverUnresolvedImmediateMatches(); await processReactionTapTimeouts();
    })().catch(() => {});
  }, 1000);
}
export async function joinQueue(userId: string, gameType: MatchGameType, stake: number) {
  const activeMatch = await db.pvpMatch.findFirst({ where: { gameType, status: "active", OR: [{ player1Id: userId }, { player2Id: userId }] } });
  if (activeMatch) { const entry = await db.matchmakingQueue.findFirst({ where: { userId, gameType, matchId: activeMatch.id } }); return { status: "matched" as const, queueId: entry?.id ?? "", matchId: activeMatch.id }; }
  const now = new Date();
  const [enabled, maintenance, configuredStakes] = await Promise.all([getConfigValue<boolean>("game." + gameType + ".enabled", true), getConfigValue<boolean>("game." + gameType + ".maintenance", false), getConfigValue<number[]>("game." + gameType + ".stakes", [])]);
  if (!enabled) throw Object.assign(new Error(gameType + " is currently unavailable"), { statusCode: 503, code: "GAME_DISABLED" });
  if (maintenance) throw Object.assign(new Error(gameType + " is under maintenance"), { statusCode: 503, code: "GAME_MAINTENANCE" });
  if (configuredStakes.length && !configuredStakes.includes(stake)) throw Object.assign(new Error("Stake $" + stake + " is not available for this game"), { statusCode: 400, code: "INVALID_STAKE" });
  const existing = await db.matchmakingQueue.findFirst({ where: { userId, gameType, stake, status: { in: ["reserved", "waiting"] }, expiresAt: { gt: now } } });
  if (existing) {
    if (existing.status === "reserved") return { status: "waiting" as const, queueId: existing.id };
    await db.$transaction(async tx => { await debitWallet(tx, userId, "game", stake); const claimed = await tx.matchmakingQueue.updateMany({ where: { id: existing.id, status: "waiting" }, data: { status: "reserved", expiresAt: new Date(Date.now() + QUEUE_TTL_MS) } }); if (!claimed.count) throw Object.assign(new Error("Queue state changed; please search again"), { statusCode: 409, code: "QUEUE_STATE_CHANGED" }); });
    return { status: "waiting" as const, queueId: existing.id };
  }
  const opponent = await db.matchmakingQueue.findFirst({ where: { gameType, stake, status: "reserved", userId: { not: userId }, expiresAt: { gt: now } }, orderBy: { createdAt: "asc" } });
  if (!opponent) { const entry = await db.$transaction(async tx => { await debitWallet(tx, userId, "game", stake); return tx.matchmakingQueue.create({ data: { userId, gameType, stake, status: "reserved", expiresAt: new Date(Date.now() + QUEUE_TTL_MS) } }); }); return { status: "waiting" as const, queueId: entry.id }; }
  try {
    await db.$transaction(async tx => { await debitWallet(tx, userId, "game", stake); const claimed = await tx.matchmakingQueue.updateMany({ where: { id: opponent.id, status: "reserved", expiresAt: { gt: now } }, data: { status: "matched" } }); if (!claimed.count) throw Object.assign(new Error("Opponent is no longer available"), { statusCode: 409, code: "OPPONENT_UNAVAILABLE" }); });
    const match = await createReservedMatchForPlayers(userId, opponent.userId, gameType, stake);
    await db.matchmakingQueue.update({ where: { id: opponent.id }, data: { matchId: match.id } });
    const mine = await db.matchmakingQueue.create({ data: { userId, gameType, stake, status: "matched", matchId: match.id, expiresAt: new Date(Date.now() + QUEUE_TTL_MS) } });
    setImmediate(() => { activateReferral(userId).catch(() => {}); activateReferral(opponent.userId).catch(() => {}); });
    return { status: "matched" as const, queueId: mine.id, matchId: match.id };
  } catch (err) {
    await db.$transaction(async tx => { await creditWallet(tx, userId, "game", stake); await creditWallet(tx, opponent.userId, "game", stake); await tx.matchmakingQueue.updateMany({ where: { id: opponent.id, status: "matched", matchId: null }, data: { status: "reserved", expiresAt: new Date(Date.now() + QUEUE_TTL_MS) } }); }).catch(() => {});
    throw err;
  }
}
export async function getQueueStatus(userId: string, queueId: string) {
  const entry = await db.matchmakingQueue.findFirst({ where: { id: queueId, userId } });
  if (!entry) throw Object.assign(new Error("Queue entry not found"), { statusCode: 404, code: "NOT_FOUND" });
  if (entry.status === "matched" && entry.matchId) return { status: "matched" as const, matchId: entry.matchId };
  if (entry.status === "cancelled" || new Date() > entry.expiresAt) {
    if (entry.status === "reserved") await db.$transaction(async tx => { const claimed = await tx.matchmakingQueue.updateMany({ where: { id: queueId, userId, status: "reserved" }, data: { status: "cancelled" } }); if (claimed.count) await creditWallet(tx, userId, "game", entry.stake); });
    else if (entry.status === "waiting") await db.matchmakingQueue.updateMany({ where: { id: queueId, userId, status: "waiting" }, data: { status: "cancelled" } });
    return { status: "cancelled" as const };
  }
  return { status: "waiting" as const };
}
export async function leaveQueue(userId: string, queueId: string) { await db.$transaction(async tx => { const entry = await tx.matchmakingQueue.findFirst({ where: { id: queueId, userId } }); if (!entry) return; if (entry.status === "reserved") { const claimed = await tx.matchmakingQueue.updateMany({ where: { id: queueId, userId, status: "reserved" }, data: { status: "cancelled" } }); if (claimed.count) await creditWallet(tx, userId, "game", entry.stake); } else if (entry.status === "waiting") await tx.matchmakingQueue.updateMany({ where: { id: queueId, userId, status: "waiting" }, data: { status: "cancelled" } }); }); }
async function createGameNotification(tx: any, userId: string, won: boolean, gameName: string, stake: number, payout: number, opponentId: string) {
  await tx.notification.create({ data: { userId, type: won ? "game_win" : "game_loss", title: won ? `🎉 ${gameName} Victory!` : `${gameName} Result`, message: won ? `You won $${payout.toFixed(2)} after staking $${stake.toFixed(2)}.` : `You lost $${stake.toFixed(2)} in ${gameName}.`, metadata: JSON.stringify({ game: gameName.toLowerCase().replace(/\s+/g, "_"), stake, payout, opponentId }) } });
}
export async function createMatchForPlayers(player1Id: string, player2Id: string, gameType: MatchGameType, stake: number) {
  const totalPool = stake * 2; const feeRate = await getGameFeeRate(gameType); const fee = totalPool * feeRate; const serverSeed = generateServerSeed(); const serverSeedHash = hashServerSeed(serverSeed); const verificationId = gameType === "reaction_tap" ? undefined : generateVerificationId(gameType);
  if (gameType === "pvp_coinflip" && randomInt(2) === 1) [player1Id, player2Id] = [player2Id, player1Id];
  const match = await db.$transaction(async tx => { for (const pid of [player1Id, player2Id]) { await debitWallet(tx, pid, "game", stake); } return tx.pvpMatch.create({ data: { gameType, stake, player1Id, player2Id, serverSeedHash, verificationId } }); });
  try { if (gameType === "dice_clash") await resolveDiceClash(match.id, player1Id, player2Id, stake, fee, totalPool, serverSeed, feeRate); else if (gameType === "pvp_coinflip") await resolveCoinFlip(match.id, player1Id, player2Id, stake, fee, totalPool, serverSeed, feeRate); } catch (err) { console.error(`[Matchmaking] Immediate settlement deferred for ${match.id}:`, err); }
  return db.pvpMatch.findUniqueOrThrow({ where: { id: match.id } });
}

export async function createReservedMatchForPlayers(player1Id: string, player2Id: string, gameType: MatchGameType, stake: number) {
  const totalPool = stake * 2; const feeRate = await getGameFeeRate(gameType); const fee = totalPool * feeRate; const serverSeed = generateServerSeed(); const serverSeedHash = hashServerSeed(serverSeed); const verificationId = gameType === "reaction_tap" ? undefined : generateVerificationId(gameType);
  if (gameType === "pvp_coinflip" && randomInt(2) === 1) [player1Id, player2Id] = [player2Id, player1Id];
  const match = await db.pvpMatch.create({ data: { gameType, stake, player1Id, player2Id, serverSeedHash, verificationId } });
  try { if (gameType === "dice_clash") await resolveDiceClash(match.id, player1Id, player2Id, stake, fee, totalPool, serverSeed, feeRate); else if (gameType === "pvp_coinflip") await resolveCoinFlip(match.id, player1Id, player2Id, stake, fee, totalPool, serverSeed, feeRate); } catch (err) { console.error(`[Matchmaking] Immediate settlement deferred for ${match.id}:`, err); }
  return db.pvpMatch.findUniqueOrThrow({ where: { id: match.id } });
}

async function resolveDiceClash(matchId:string,p1Id:string,p2Id:string,stake:number,fee:number,totalPool:number,serverSeed:string,feeRate:number){const clientSeed=generateClientSeed(...[p1Id,p2Id].sort(),matchId);const{p1Roll,p2Roll}=deriveDiceClash(serverSeed,clientSeed,1);const winnerId=p1Roll>p2Roll?p1Id:p2Roll>p1Roll?p2Id:(p1Id<p2Id?p1Id:p2Id);const loserId=winnerId===p1Id?p2Id:p1Id;const payout=totalPool-fee;await db.$transaction(async tx=>{const guard=await tx.pvpMatch.updateMany({where:{id:matchId,status:"active"},data:{status:"settled",winnerId,resultData:JSON.stringify({p1Roll,p2Roll,winnerId}),settledAt:new Date(),serverSeed,clientSeed,nonce:1}});if(!guard.count)return;await creditWallet(tx,winnerId,"game",payout);await writeLedgerEntry(tx,{userId:winnerId,type:"game_win",toWallet:"game",amount:payout,description:"Dice Clash win",referenceId:matchId,referenceType:"pvp_match"});await writeLedgerEntry(tx,{userId:loserId,type:"game_loss",fromWallet:"game",amount:stake,description:"Dice Clash loss",referenceId:matchId,referenceType:"pvp_match"});await recordGameResult({tx,userId:winnerId,gameType:"dice_clash",wagered:stake,won:true,payout});await recordGameResult({tx,userId:loserId,gameType:"dice_clash",wagered:stake,won:false,payout:0});await createGameNotification(tx,winnerId,true,"Dice Clash",stake,payout,loserId);await createGameNotification(tx,loserId,false,"Dice Clash",stake,0,winnerId);const userFee=stake*feeRate;await createGameFeeJobInTx(tx,{userId:winnerId,userFee,isMultiGame:false,eventRefId:matchId});await createGameFeeJobInTx(tx,{userId:loserId,userFee,isMultiGame:false,eventRefId:matchId})})}
async function resolveCoinFlip(matchId:string,p1Id:string,p2Id:string,stake:number,fee:number,totalPool:number,serverSeed:string,feeRate:number){const clientSeed=generateClientSeed(...[p1Id,p2Id].sort(),matchId);const coinFlip=deriveCoinFlip(serverSeed,clientSeed,1);const p1Side: "heads" | "tails" = randomInt(2) === 0 ? "heads" : "tails";const p2Side: "heads" | "tails" = p1Side === "heads" ? "tails" : "heads";const winnerId=coinFlip===p1Side?p1Id:p2Id;const loserId=winnerId===p1Id?p2Id:p1Id;const payout=totalPool-fee;await db.$transaction(async tx=>{const guard=await tx.pvpMatch.updateMany({where:{id:matchId,status:"active"},data:{status:"settled",winnerId,resultData:JSON.stringify({p1Side,p2Side,coinFlip,winnerId}),settledAt:new Date(),serverSeed,clientSeed,nonce:1}});if(!guard.count)return;await creditWallet(tx,winnerId,"game",payout);await writeLedgerEntry(tx,{userId:winnerId,type:"game_win",toWallet:"game",amount:payout,description:"Coin Flip win",referenceId:matchId,referenceType:"pvp_match"});await writeLedgerEntry(tx,{userId:loserId,type:"game_loss",fromWallet:"game",amount:stake,description:"Coin Flip loss",referenceId:matchId,referenceType:"pvp_match"});await recordGameResult({tx,userId:winnerId,gameType:"pvp_coinflip",wagered:stake,won:true,payout});await recordGameResult({tx,userId:loserId,gameType:"pvp_coinflip",wagered:stake,won:false,payout:0});await createGameNotification(tx,winnerId,true,"Coin Flip",stake,payout,loserId);await createGameNotification(tx,loserId,false,"Coin Flip",stake,0,winnerId);const userFee=stake*feeRate;await createGameFeeJobInTx(tx,{userId:winnerId,userFee,isMultiGame:false,eventRefId:matchId});await createGameFeeJobInTx(tx,{userId:loserId,userFee,isMultiGame:false,eventRefId:matchId})})}
export async function getMatch(userId:string,matchId:string){const match=await db.pvpMatch.findFirst({where:{id:matchId,OR:[{player1Id:userId},{player2Id:userId}]},include:{player1:{include:{profile:{select:{username:true,avatarUrl:true}}}},player2:{include:{profile:{select:{username:true,avatarUrl:true}}}}}});if(!match)throw Object.assign(new Error("Match not found"),{statusCode:404,code:"NOT_FOUND"});const isPlayer1=match.player1Id===userId;const opponent=isPlayer1?match.player2:match.player1;const totalPool=match.stake*2;const fee=totalPool*await getGameFeeRate(match.gameType as MatchGameType);return{matchId:match.id,gameType:match.gameType,stake:match.stake,totalPool,platformFee:fee,status:match.status,isPlayer1,opponent:{username:opponent.profile?.username??"Player",userId:opponent.id,avatar:opponent.profile?.avatarUrl??null},result:match.resultData?JSON.parse(match.resultData):null,winnerId:match.winnerId,youWon:match.winnerId===userId,payout:match.winnerId===userId?totalPool-fee:0,createdAt:match.createdAt.toISOString(),settledAt:match.settledAt?.toISOString()??null,signalSentAt:match.signalSentAt?.toISOString()??null,yourReady:isPlayer1?match.player1Ready:match.player2Ready,opponentReady:isPlayer1?match.player2Ready:match.player1Ready}}
export async function signalReady(userId:string,matchId:string){return db.$transaction(async tx=>{const match=await tx.pvpMatch.findFirst({where:{id:matchId,status:"active",OR:[{player1Id:userId},{player2Id:userId}]}});if(!match)throw Object.assign(new Error("Match not found"),{statusCode:404,code:"NOT_FOUND"});await tx.$queryRaw`SELECT id FROM pvp_matches WHERE id = ${matchId} FOR UPDATE`;const isPlayer1=match.player1Id===userId;const data:any=isPlayer1?{player1Ready:true}:{player2Ready:true};const updated=await tx.pvpMatch.update({where:{id:matchId},data});if(updated.player1Ready&&updated.player2Ready&&!updated.signalSentAt){const delayMs=SIGNAL_DELAY_MS[randomInt(SIGNAL_DELAY_MS.length)];const signalSentAt=new Date(Date.now()+delayMs);const final=await tx.pvpMatch.update({where:{id:matchId},data:{signalSentAt}});return{signalSentAt:final.signalSentAt!.toISOString(),delayMs}}return{waiting:true}})}
async function submitTap(userId:string,matchId:string,tapMs:number){if(!Number.isFinite(tapMs)||tapMs<-60000||tapMs>60000)throw Object.assign(new Error("Invalid reaction time"),{statusCode:400,code:"INVALID_TAP"});const result=await db.$transaction(async tx=>{const match=await tx.pvpMatch.findFirst({where:{id:matchId,status:"active",OR:[{player1Id:userId},{player2Id:userId}]}});if(!match||!match.signalSentAt)throw Object.assign(new Error("Signal not yet sent"),{statusCode:400,code:"SIGNAL_NOT_SENT"});await tx.$queryRaw`SELECT id FROM pvp_matches WHERE id = ${matchId} FOR UPDATE`;const isPlayer1=match.player1Id===userId;const updateData:any=isPlayer1?{player1TapMs:tapMs}:{player2TapMs:tapMs};const updated=await tx.pvpMatch.update({where:{id:matchId},data:updateData});return updated});if(result.player1TapMs!==null&&result.player2TapMs!==null)await resolveReactionTap(matchId,result.player1Id,result.player2Id,result.stake,result.player1TapMs,result.player2TapMs);return{submitted:true}}
async function resolveReactionTap(matchId:string,p1Id:string,p2Id:string,stake:number,p1Tap:number,p2Tap:number){const p1Forfeited=p1Tap<0,p2Forfeited=p2Tap<0;if(p1Forfeited&&p2Forfeited){await db.$transaction(async tx=>{const guard=await tx.pvpMatch.updateMany({where:{id:matchId,status:"active"},data:{status:"cancelled",resultData:JSON.stringify({p1TapMs:p1Tap,p2TapMs:p2Tap,void:true}),settledAt:new Date()}});if(!guard.count)return;for(const pid of[p1Id,p2Id]){await creditWallet(tx,pid,"game",stake);await writeLedgerEntry(tx,{userId:pid,type:"transfer",toWallet:"game",amount:stake,description:"Reaction Tap void — refund",referenceId:matchId,referenceType:"pvp_match"});await recordGameResult({tx,userId:pid,gameType:"reaction_tap",wagered:stake,won:false,payout:stake});await createGameNotification(tx,pid,false,"Reaction Tap",stake,stake,pid===p1Id?p2Id:p1Id)}});return}const totalPool=stake*2;const feeRate=await getGameFeeRate("reaction_tap");const payout=totalPool-totalPool*feeRate;const winnerId=p1Forfeited?p2Id:p2Forfeited?p1Id:p1Tap===p2Tap?(p1Id<p2Id?p1Id:p2Id):p1Tap<p2Tap?p1Id:p2Id;const loserId=winnerId===p1Id?p2Id:p1Id;await db.$transaction(async tx=>{const guard=await tx.pvpMatch.updateMany({where:{id:matchId,status:"active"},data:{status:"settled",winnerId,resultData:JSON.stringify({p1TapMs:p1Tap,p2TapMs:p2Tap,winnerId,p1Forfeited,p2Forfeited}),settledAt:new Date()}});if(!guard.count)return;await creditWallet(tx,winnerId,"game",payout);await writeLedgerEntry(tx,{userId:winnerId,type:"game_win",toWallet:"game",amount:payout,description:"Reaction Tap win",referenceId:matchId,referenceType:"pvp_match"});await writeLedgerEntry(tx,{userId:loserId,type:"game_loss",fromWallet:"game",amount:stake,description:"Reaction Tap loss",referenceId:matchId,referenceType:"pvp_match"});await recordGameResult({tx,userId:winnerId,gameType:"reaction_tap",wagered:stake,won:true,payout});await recordGameResult({tx,userId:loserId,gameType:"reaction_tap",wagered:stake,won:false,payout:0});await createGameNotification(tx,winnerId,true,"Reaction Tap",stake,payout,loserId);await createGameNotification(tx,loserId,false,"Reaction Tap",stake,0,winnerId)})}
async function processReactionTapTimeouts(){const now=new Date();const matches=await db.pvpMatch.findMany({where:{gameType:"reaction_tap",status:"active",signalSentAt:{not:null,lt:new Date(now.getTime()-REACTION_TAP_TIMEOUT_MS)}},take:100});for(const m of matches){const p1=m.player1TapMs,p2=m.player2TapMs;if(p1!==null&&p2!==null)await resolveReactionTap(m.id,m.player1Id,m.player2Id,m.stake,p1,p2);else if(p1!==null)await resolveReactionTap(m.id,m.player1Id,m.player2Id,m.stake,p1,-1);else if(p2!==null)await resolveReactionTap(m.id,m.player1Id,m.player2Id,m.stake,-1,p2);else await resolveReactionTap(m.id,m.player1Id,m.player2Id,m.stake,-1,-1)}}
async function recoverUnresolvedImmediateMatches(){const matches=await db.pvpMatch.findMany({where:{status:"active",gameType:{in:["dice_clash","pvp_coinflip"]}},take:100});for(const m of matches){const feeRate=await getGameFeeRate(m.gameType as MatchGameType);const totalPool=m.stake*2;const fee=totalPool*feeRate;if(!m.serverSeed)continue;try{if(m.gameType==="dice_clash")await resolveDiceClash(m.id,m.player1Id,m.player2Id,m.stake,fee,totalPool,m.serverSeed,feeRate);else await resolveCoinFlip(m.id,m.player1Id,m.player2Id,m.stake,fee,totalPool,m.serverSeed,feeRate)}catch{}}}
