import { createHmac, createHash, randomBytes } from "crypto";

const VID_PREFIXES: Record<string, string> = {
  color_game: "BZM-CP", spin_battle: "BZM-SB", pvp_coinflip: "BZM-CF", dice_clash: "BZM-DC", dice_royale: "BZM-DR", dice_arena: "BZM-DA",
};
export function generateVerificationId(gameType: string): string { const prefix = VID_PREFIXES[gameType]; if (!prefix) throw new Error(`No verification ID prefix for game type: ${gameType}`); return `${prefix}-${randomBytes(4).toString("hex").toUpperCase()}`; }
export function decodeVerificationId(verificationId: string): { gameType: string; model: "game_round" | "pvp_match" | "dice_round" } | null { const upper=verificationId.toUpperCase(); if(upper.startsWith("BZM-CP-"))return{gameType:"color_game",model:"game_round"}; if(upper.startsWith("BZM-SB-"))return{gameType:"spin_battle",model:"game_round"}; if(upper.startsWith("BZM-CF-"))return{gameType:"pvp_coinflip",model:"pvp_match"}; if(upper.startsWith("BZM-DC-"))return{gameType:"dice_clash",model:"pvp_match"}; if(upper.startsWith("BZM-DR-"))return{gameType:"dice_royale",model:"dice_round"}; if(upper.startsWith("BZM-DA-"))return{gameType:"dice_arena",model:"dice_round"}; return null; }
export function generateServerSeed(): string { return randomBytes(32).toString("hex"); }
export function hashServerSeed(seed: string): string { return createHash("sha256").update(seed).digest("hex"); }
export function generateClientSeed(...publicParts: string[]): string { return createHash("sha256").update(publicParts.join("|")).digest("hex"); }
function getResultBytes(serverSeed:string,clientSeed:string,nonce:number):Buffer{const h=createHmac("sha256",serverSeed);h.update(`${clientSeed}:${nonce}`);return Buffer.from(h.digest("hex"),"hex");}
function uint32At(buf:Buffer,index:number):number{return buf.readUInt32BE((index*4)%28);}
export function deriveColorResult(serverSeed:string,clientSeed:string,nonce:number):"red"|"blue"{return getResultBytes(serverSeed,clientSeed,nonce)[0]%2===0?"red":"blue";}
export function deriveCoinFlip(serverSeed:string,clientSeed:string,nonce:number):"heads"|"tails"{return getResultBytes(serverSeed,clientSeed,nonce)[0]%2===0?"heads":"tails";}
export function deriveDiceClash(serverSeed:string,clientSeed:string,nonce:number):{p1Roll:number;p2Roll:number}{const b=getResultBytes(serverSeed,clientSeed,nonce);let p1Roll=(uint32At(b,0)%6)+1,p2Roll=(uint32At(b,1)%6)+1;for(let i=2;p1Roll===p2Roll&&i<7;i+=2){p1Roll=(uint32At(b,i)%6)+1;p2Roll=(uint32At(b,i+1)%6)+1;}return{p1Roll,p2Roll};}
export function deriveDiceRolls(serverSeed:string,clientSeed:string,nonce:number,sortedPlayerIds:string[]):Record<string,number>{const b=getResultBytes(serverSeed,clientSeed,nonce);const rolls:Record<string,number>={};for(let i=0;i<sortedPlayerIds.length;i++)rolls[sortedPlayerIds[i]]=(uint32At(b,i)%6)+1;return rolls;}
export function deriveTieBreakRolls(serverSeed:string,clientSeed:string,nonce:number,tbRound:number,candidateIds:string[]):Record<string,number>{const h=createHmac("sha256",serverSeed);h.update(`${clientSeed}:${nonce}:tb:${tbRound}`);const b=Buffer.from(h.digest("hex"),"hex"),rolls:Record<string,number>={};for(let i=0;i<candidateIds.length;i++)rolls[candidateIds[i]]=(uint32At(b,i)%6)+1;return rolls;}
export function deriveSpinWinner(serverSeed:string,clientSeed:string,nonce:number,sortedPlayerIds:string[],playerWeights:Record<string,number>={}):string{if(!sortedPlayerIds.length)throw new Error("Spin Battle requires at least one player");const scale=1_000_000,weights=sortedPlayerIds.map(id=>Math.max(0,Math.round((playerWeights[id]??0)*scale))),total=weights.reduce((a,b)=>a+b,0);if(total<=0)throw new Error("Spin Battle requires positive player stakes");const TWO64=18446744073709551616n;for(let attempt=0;attempt<16;attempt++){const b=getResultBytes(serverSeed,clientSeed,nonce+attempt),x=(BigInt(uint32At(b,0))<<32n)|BigInt(uint32At(b,1)),totalBig=BigInt(total),limit=(TWO64/totalBig)*totalBig;if(x>=limit)continue;let cursor=Number(x%totalBig);for(let i=0;i<weights.length;i++){if(cursor<weights[i])return sortedPlayerIds[i];cursor-=weights[i];}}return sortedPlayerIds[weights.findIndex(w=>w>0)];}
export interface VerifyInput{serverSeed:string;serverSeedHash:string;clientSeed:string;nonce:number;gameType:string;claimedResult?:any;playerIds?:string[];}
export interface VerifyOutput{hashValid:boolean;resultValid:boolean|null;computedResult:any;algorithm:string;explanation:string;}

export function verifyFairness(input:VerifyInput):VerifyOutput{
 const hashValid=hashServerSeed(input.serverSeed)===input.serverSeedHash;
 const algorithm=`HMAC-SHA256(serverSeed, "${input.clientSeed}:${input.nonce}")`;
 let computedResult:any=null,resultValid:boolean|null=null,explanation="";
 try{
  switch(input.gameType){
   case "color_game": { computedResult=deriveColorResult(input.serverSeed,input.clientSeed,input.nonce); resultValid=input.claimedResult!=null?computedResult===input.claimedResult:null; explanation="Color is derived from byte 0 of HMAC-SHA256: even = red, odd = blue."; break; }
   case "pvp_coinflip": { const coinFlip=deriveCoinFlip(input.serverSeed,input.clientSeed,input.nonce); computedResult={coinFlip}; resultValid=input.claimedResult?.coinFlip!=null?coinFlip===input.claimedResult.coinFlip:null; explanation="Coin side is derived from byte 0 of HMAC-SHA256: even = heads, odd = tails."; break; }
   case "dice_clash": { computedResult=deriveDiceClash(input.serverSeed,input.clientSeed,input.nonce); resultValid=input.claimedResult?.p1Roll!=null?computedResult.p1Roll===input.claimedResult.p1Roll&&computedResult.p2Roll===input.claimedResult.p2Roll:null; explanation="Both dice rolls are deterministically derived from HMAC-SHA256; equal rolls use the deterministic tie-break derivation."; break; }
   case "spin_battle": { const weights=input.claimedResult?.playerBets as Record<string,number>|undefined,ids=input.claimedResult?.playerIds as string[]|undefined; if(!weights||!ids?.length){explanation="Stake-proportional verification requires the settled player IDs and locked stakes.";break;}const ordered=[...ids].sort(),weightObject=Object.fromEntries(ordered.map(id=>[id,Number(weights[id]??0)]));const winner=deriveSpinWinner(input.serverSeed,input.clientSeed,input.nonce,ordered,weightObject);computedResult={winner};resultValid=input.claimedResult?.winner!=null?winner===input.claimedResult.winner:null;explanation="Winner is selected from locked stakes using unbiased 64-bit HMAC sampling.";break; }
   case "dice_royale":
   case "dice_arena": { const ids=[...(input.playerIds??input.claimedResult?.playerIds??[])].map(String).sort(); if(!ids.length){explanation="Dice verification requires the settled player ID list.";break;} const rolls=deriveDiceRolls(input.serverSeed,input.clientSeed,input.nonce,ids); let max=Math.max(...Object.values(rolls)),candidates=ids.filter(id=>rolls[id]===max),tbRound=1; while(candidates.length>1){const tb=deriveTieBreakRolls(input.serverSeed,input.clientSeed,input.nonce,tbRound,candidates);Object.assign(rolls,tb);max=Math.max(...candidates.map(id=>rolls[id]));candidates=candidates.filter(id=>rolls[id]===max);tbRound++;} const winnerId=candidates[0];computedResult={rolls,winnerId}; const claimed=input.claimedResult; resultValid=claimed?.winnerId!=null?winnerId===claimed.winnerId&&JSON.stringify(rolls)===JSON.stringify(claimed.rolls):null; explanation="Each player receives a deterministic HMAC-derived d6 roll in stable sorted player-ID order; ties use deterministic sub-nonces.";break; }
   default: explanation=`Unknown game type: ${input.gameType}`;
  }
 }catch{explanation="Verification error — check the stored round data.";}
 return{hashValid,resultValid,computedResult,algorithm,explanation};
}
