import Fastify from "fastify";
import cors from "@fastify/cors";
import helmet from "@fastify/helmet";
import rateLimit from "@fastify/rate-limit";
import { config } from "./config";
import { errorHandler } from "./middleware/errorHandler";
import { validateProductionConfig } from "./security/productionCheck";
import { authRoutes } from "./modules/auth/auth.routes";
import { usersRoutes } from "./modules/users/users.routes";
import { walletsRoutes } from "./modules/wallets/wallets.routes";
import { transactionsRoutes } from "./modules/transactions/transactions.routes";
import { depositsRoutes } from "./modules/deposits/deposits.routes";
import { withdrawalsRoutes } from "./modules/withdrawals/withdrawals.routes";
import { kycRoutes } from "./modules/kyc/kyc.routes";
import { adminKycRoutes } from "./modules/admin/kyc/admin.kyc.routes";
import { tasksRoutes } from "./modules/tasks/tasks.routes";
import { proofsRoutes } from "./modules/tasks/proofs.routes";
import { adminTasksRoutes } from "./modules/admin/tasks/admin.tasks.routes";
import { adminProofsRoutes } from "./modules/admin/proofs/admin.proofs.routes";
import { vipRoutes } from "./modules/vip/vip.routes";
import { referralsRoutes } from "./modules/referrals/referrals.routes";
import { affiliatesRoutes } from "./modules/affiliates/affiliates.routes";
import { gamesSharedRoutes } from "./modules/games/games.routes";
import { colorGameRoutes } from "./modules/games/colorGame/colorGame.routes";
import { spinBattleRoutes } from "./modules/games/spinBattle/spinBattle.routes";
import { matchmakingRoutes } from "./modules/games/matchmaking/matchmaking.routes";
import { diceRoyaleRoutes } from "./modules/games/diceRoyale/diceRoyale.routes";
import { diceArenaRoutes } from "./modules/games/diceArena/diceArena.routes";
import { provablyFairRoutes } from "./modules/games/provablyFair.routes";
import { startColorGameLobbies } from "./modules/games/colorGame/colorGame.service";
import { startSpinBattleLobbies } from "./modules/games/spinBattle/spinBattle.service";
import { startQueueCleanup } from "./modules/games/matchmaking/matchmaking.service";
import { privateRoomRoutes } from "./modules/games/privateRoom/privateRoom.routes";
import { cleanupExpiredRooms } from "./modules/games/privateRoom/privateRoom.service";
import { notificationsRoutes } from "./modules/notifications/notifications.routes";
import { platformRoutes } from "./modules/platform/platform.routes";
import { publicRoutes } from "./modules/platform/public.routes";
import { adminStatsRoutes } from "./modules/admin/stats/admin.stats.routes";
import { adminUsersRoutes } from "./modules/admin/users/admin.users.routes";
import { adminDepositsRoutes } from "./modules/admin/deposits/admin.deposits.routes";
import { adminWithdrawalsRoutes } from "./modules/admin/withdrawals/admin.withdrawals.routes";
import { adminTransactionsRoutes } from "./modules/admin/transactions/admin.transactions.routes";
import { adminConfigRoutes } from "./modules/admin/config/admin.config.routes";
import { seedDefaultConfig, getConfigValue } from "./modules/admin/config/admin.config.service";
import { adminGamesRoutes } from "./modules/admin/games/admin.games.routes";
import { seedDefaultRooms } from "./modules/admin/games/admin.games.service";
import { adminReferralsRoutes } from "./modules/admin/referrals/admin.referrals.routes";
import { adminAffiliatesRoutes } from "./modules/admin/affiliates/admin.affiliates.routes";
import { adminVipRoutes } from "./modules/admin/vip/admin.vip.routes";
import { maintenanceModeHook } from "./middleware/maintenanceMode";
import { adminNotificationsRoutes } from "./modules/admin/notifications/admin.notifications.routes";
import { adminContentRoutes } from "./modules/admin/content/admin.content.routes";
import { adminPagesRoutes } from "./modules/admin/pages/admin.pages.routes";
import { adminTextRoutes } from "./modules/admin/text/admin.text.routes";
import { seedDefaultText } from "./modules/admin/text/admin.text.service";
import { seedDefaultPages } from "./modules/admin/pages/admin.pages.service";
import { adminAnalyticsRoutes } from "./modules/admin/analytics/admin.analytics.routes";
import { adminDeveloperRoutes } from "./modules/admin/developer/admin.developer.routes";
import { adminSecurityRoutes } from "./modules/admin/security/admin.security.routes";
import { footballRoutes } from "./modules/football/football.routes";
import { adminFootballRoutes } from "./modules/football/admin.football.routes";
import { adminAiRoutes } from "./modules/football/admin.ai.routes";
import { ambassadorsRoutes, adminAmbassadorsRoutes } from "./modules/ambassadors/ambassadors.routes";
import { challengesRoutes, adminChallengesRoutes } from "./modules/challenges/challenges.routes";
import { promotionsRoutes, adminPromotionsRoutes } from "./modules/promotions/promotions.routes";
import { seedDefaultFeaturedPricing, runScheduledPromotions } from "./modules/promotions/promotions.service";
import { adminCurrencyRoutes } from "./modules/admin/currency/admin.currency.routes";
import { seedDefaultCurrencies, listEnabledCurrencies, getDefaultCurrency } from "./modules/admin/currency/admin.currency.service";
import { adminLanguageRoutes } from "./modules/admin/language/admin.language.routes";
import { seedDefaultLanguages, listEnabledLanguages } from "./modules/admin/language/admin.language.service";
import { adminTranslationRoutes } from "./modules/admin/translation/admin.translation.routes";
import { seedDefaultTranslationKeys, getTranslationsForLanguage } from "./modules/admin/translation/admin.translation.service";
import { adminFeaturesRoutes } from "./modules/admin/features/admin.features.routes";
import { getBranding } from "./modules/admin/branding/admin.branding.service";
import { auctionsRoutes } from "./modules/auctions/auctions.routes";
import { adminAuctionsRoutes } from "./modules/auctions/admin.auctions.routes";
import { runAuctionScheduler } from "./modules/auctions/auctions.service";
import { adminWalletsRoutes } from "./modules/admin/wallets/admin.wallets.routes";
import { startWithdrawalLimitResetJob } from "./jobs/withdrawalLimitReset";
import { startScreenshotRetentionJob } from "./jobs/screenshotRetention";
import { startAuditLogRetentionJob } from "./jobs/auditLogRetention";
import { startStreakReminderJob } from "./jobs/streakReminder";
import { startCryptoDepositMonitor } from "./jobs/cryptoDepositMonitor";
import { startCommissionJobWorker } from "./jobs/commissionJob";
import { startAiAnalysisWorker } from "./jobs/aiAnalysisWorker";
import { startFootballSyncWorker } from "./jobs/footballSyncWorker";
import { startAutoPublishWorker } from "./jobs/autoPublishWorker";

validateProductionConfig();
const app = Fastify({ logger: { level: config.env === "production" ? "info" : "warn" }, bodyLimit: 1 * 1024 * 1024 });
function authenticatedRateLimitKey(req: any): string { const authorization = String(req.headers.authorization ?? ""); return authorization ? `${req.ip}:${authorization}` : `anon:${req.ip}`; }

async function bootstrap() {
  await app.register(helmet, { contentSecurityPolicy: { directives: { defaultSrc: ["'self'"], scriptSrc: ["'self'"], styleSrc: ["'self'", "'unsafe-inline'"], imgSrc: ["'self'", "data:", "https:"], connectSrc: ["'self'"], frameSrc: ["'none'"], objectSrc: ["'none'"], upgradeInsecureRequests: config.env === "production" ? [] : null } }, hsts: config.env === "production" ? { maxAge: 31536000, includeSubDomains: true, preload: true } : false, xFrameOptions: { action: "deny" }, xContentTypeOptions: true, referrerPolicy: { policy: "strict-origin-when-cross-origin" } });
  await app.register(cors, { origin: config.cors.origins, credentials: true, methods: ["GET","POST","PATCH","PUT","DELETE","OPTIONS"] });
  await app.register(rateLimit, { global: true, max: 200, timeWindow: "1 minute", keyGenerator: authenticatedRateLimitKey, errorResponseBuilder: () => ({ error: { code: "RATE_LIMITED", message: "Too many requests — please slow down" } }) });
  app.get("/health", async () => ({ status: "ok", phase: "3H", env: config.env, timestamp: new Date().toISOString() }));
  app.register(async (scope) => { await scope.register(rateLimit, { max: 5, timeWindow: "1 minute", keyGenerator: (r) => r.ip }); scope.register(authRoutes, { prefix: "/api/v1/auth" }); });
  app.register(usersRoutes, { prefix: "/api/v1/users" }); app.register(walletsRoutes, { prefix: "/api/v1/wallets" });
  app.register(async (scope) => { await scope.register(rateLimit, { max: 10, timeWindow: "1 minute", keyGenerator: authenticatedRateLimitKey }); scope.register(transactionsRoutes, { prefix: "/api/v1/transactions" }); scope.register(depositsRoutes, { prefix: "/api/v1/deposits" }); scope.register(withdrawalsRoutes, { prefix: "/api/v1/withdrawals" }); });
  app.register(kycRoutes, { prefix: "/api/v1/kyc" }); app.register(tasksRoutes, { prefix: "/api/v1/tasks" }); app.register(proofsRoutes, { prefix: "/api/v1/tasks" }); app.register(vipRoutes, { prefix: "/api/v1/vip" }); app.register(referralsRoutes, { prefix: "/api/v1/referrals" }); app.register(affiliatesRoutes, { prefix: "/api/v1/affiliates" });
  app.register(async (scope) => { await scope.register(rateLimit, { max: 120, timeWindow: "1 minute", keyGenerator: authenticatedRateLimitKey }); scope.register(gamesSharedRoutes, { prefix: "/api/v1/games" }); scope.register(colorGameRoutes, { prefix: "/api/v1/games/color" }); scope.register(spinBattleRoutes, { prefix: "/api/v1/games/spin" }); scope.register(matchmakingRoutes, { prefix: "/api/v1/games" }); scope.register(privateRoomRoutes, { prefix: "/api/v1/games" }); scope.register(diceRoyaleRoutes, { prefix: "/api/v1/games/dice-royale" }); scope.register(diceArenaRoutes, { prefix: "/api/v1/games/dice-arena" }); scope.register(provablyFairRoutes, { prefix: "/api/v1/games/fairness" }); });
  app.register(notificationsRoutes, { prefix: "/api/v1/notifications" }); app.register(footballRoutes, { prefix: "/api/v1/football" }); app.register(ambassadorsRoutes, { prefix: "/api/v1/ambassadors" }); app.register(challengesRoutes, { prefix: "/api/v1/challenges" }); app.register(promotionsRoutes, { prefix: "/api/v1/promotions" }); app.register(auctionsRoutes, { prefix: "/api/v1/auctions" }); app.register(platformRoutes, { prefix: "/api/v1/platform" }); app.register(publicRoutes, { prefix: "/api/v1/public" });
  app.addHook("onRequest", maintenanceModeHook);
  app.register(async (scope) => { await scope.register(rateLimit, { max: 60, timeWindow: "1 minute", keyGenerator: authenticatedRateLimitKey }); scope.register(adminKycRoutes, { prefix: "/api/v1/admin/kyc" }); scope.register(adminTasksRoutes, { prefix: "/api/v1/admin/tasks" }); scope.register(adminProofsRoutes, { prefix: "/api/v1/admin/proofs" }); scope.register(adminStatsRoutes, { prefix: "/api/v1/admin/stats" }); scope.register(adminUsersRoutes, { prefix: "/api/v1/admin/users" }); scope.register(adminDepositsRoutes, { prefix: "/api/v1/admin/deposits" }); scope.register(adminWithdrawalsRoutes, { prefix: "/api/v1/admin/withdrawals" }); scope.register(adminTransactionsRoutes, { prefix: "/api/v1/admin/transactions" }); scope.register(adminConfigRoutes, { prefix: "/api/v1/admin/config" }); scope.register(adminGamesRoutes, { prefix: "/api/v1/admin/games" }); scope.register(adminReferralsRoutes, { prefix: "/api/v1/admin/referrals" }); scope.register(adminAffiliatesRoutes, { prefix: "/api/v1/admin/affiliates" }); scope.register(adminVipRoutes, { prefix: "/api/v1/admin/vip" }); scope.register(adminNotificationsRoutes, { prefix: "/api/v1/admin/notifications" }); scope.register(adminContentRoutes, { prefix: "/api/v1/admin/content" }); scope.register(adminPagesRoutes, { prefix: "/api/v1/admin/pages" }); scope.register(adminTextRoutes, { prefix: "/api/v1/admin/text" }); scope.register(adminAnalyticsRoutes, { prefix: "/api/v1/admin/analytics" }); scope.register(adminDeveloperRoutes, { prefix: "/api/v1/admin/developer" }); scope.register(adminSecurityRoutes, { prefix: "/api/v1/admin/security" }); scope.register(adminFootballRoutes, { prefix: "/api/v1/admin/football" }); scope.register(adminAiRoutes, { prefix: "/api/v1/admin/ai" }); scope.register(adminAmbassadorsRoutes, { prefix: "/api/v1/admin/ambassadors" }); scope.register(adminChallengesRoutes, { prefix: "/api/v1/admin/challenges" }); scope.register(adminPromotionsRoutes, { prefix: "/api/v1/admin/promotions" }); scope.register(adminAuctionsRoutes, { prefix: "/api/v1/admin/auctions" }); scope.register(adminWalletsRoutes, { prefix: "/api/v1/admin/wallets" }); scope.register(adminCurrencyRoutes, { prefix: "/api/v1/admin/currency" }); scope.register(adminLanguageRoutes, { prefix: "/api/v1/admin/language" }); scope.register(adminTranslationRoutes, { prefix: "/api/v1/admin/translation" }); scope.register(adminFeaturesRoutes, { prefix: "/api/v1/admin/features" }); });
  app.get("/api/v1/languages", async (_req, reply) => reply.send({ data: await listEnabledLanguages() }));
  app.get("/api/v1/translations/:code", async (req, reply) => { const { code } = req.params as { code: string }; return reply.send({ data: await getTranslationsForLanguage(code) }); });
  app.get("/api/v1/platform/branding", async (_req, reply) => reply.send({ data: await getBranding() })); app.get("/api/v1/currencies/default", async (_req, reply) => reply.send({ data: await getDefaultCurrency() })); app.get("/api/v1/currencies", async (_req, reply) => reply.send({ data: await listEnabledCurrencies() }));
  app.setErrorHandler(errorHandler); app.setNotFoundHandler((req, reply) => reply.status(404).send({ error: { code: "NOT_FOUND", message: `${req.method} ${req.url} not found` } }));
  await seedDefaultConfig(); await seedDefaultCurrencies(); await seedDefaultRooms(); await seedDefaultFeaturedPricing(); await seedDefaultText(); await seedDefaultPages(); await seedDefaultLanguages(); await seedDefaultTranslationKeys();
  const debugMode = await getConfigValue<boolean>("system.debug_mode", false); if (debugMode) app.log.level = "debug";
  startWithdrawalLimitResetJob(); startScreenshotRetentionJob(); startAuditLogRetentionJob(); startStreakReminderJob(); await startColorGameLobbies(); await startSpinBattleLobbies(); startQueueCleanup(); setInterval(() => cleanupExpiredRooms(), 60_000); startCryptoDepositMonitor(); startCommissionJobWorker(); startAiAnalysisWorker(); startFootballSyncWorker(); startAutoPublishWorker(); setInterval(() => { runScheduledPromotions().catch(() => {}); }, 60_000); setInterval(() => { runAuctionScheduler().catch(() => {}); }, 30_000);
  await app.listen({ port: config.port, host: config.host }); console.log(`Bitzimi backend (Phase 3H) — ${config.host}:${config.port}`);
  const shutdown = async (signal: string) => { console.log(`[Shutdown] ${signal} received — closing server gracefully`); await app.close(); console.log("[Shutdown] Server closed. Exiting."); process.exit(0); }; process.on("SIGTERM", () => shutdown("SIGTERM")); process.on("SIGINT", () => shutdown("SIGINT"));
}
bootstrap().catch(err => { console.error("Startup failed:", err); process.exit(1); });
